#!/bin/bash

# Building the query string was done by playing with the REST
# interface at https://dhsgis.wi.gov/server/rest/services/DHS_COVID19/COVID19_WI/FeatureServer/10/query?outFields=*&where=1%3D1
# and iteratively adding fields listed below the form there.

if [ $1"." == "." ]
then
	echo "$0 needs a directory for data"
	exit 4
fi

if [ $2"." == "." ]
then
	echo "$0 needs a data file name"
	exit 4
fi

if [ $3"." == "." ]
then
	echo "$0 needs a directory for the log"
	exit 4
fi

qry='https://dhsgis.wi.gov/server/rest/services/DHS_COVID19/COVID19_WI/FeatureServer/10/query?where=GEO+%3D+%27State%27&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=DATE%2CDEATHS%2CDTH_NEW%2CTEST_NEW%2CPOS_NEW&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&gdbVersion=&historicMoment=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=DATE&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=&resultOffset=&resultRecordCount=&returnTrueCurves=false&sqlFormat=none&f=pjson'
odoc=$1$2
log=$3"log"

#echo "${odoc}"
#echo "${qry}"

wget -a ${log} --no-directories --wait 30 --random-wait --output-document ${odoc} ${qry}

myRC=$?
echo "wget rc = " ${myRC}

exit ${myRC}

